services:
  dev-db:
    # image: postgres:16.1-alpine3.19
    container_name: dev-db
    restart: always
    hostname: dev-db
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - internal

  db_dashboard:
    image: adminer
    container_name: db_dashboard
    restart: always
    ports:
      - 8081:8080
    networks:
      - internal

  mcp:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    ports:
      - "8050:8000"
    depends_on:
      - dev-db
    networks:
      - internal
    env_file:
      - .env

volumes:
  postgres_data:

networks:
  internal:
