"""empty message

Revision ID: 368d12da26fd
Revises: bf152dacdc72
Create Date: 2024-10-05 18:05:48.544244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '368d12da26fd'
down_revision: Union[str, None] = 'bf152dacdc72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_to_stock_symbol', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_to_stock_symbol', 'created_at')
    # ### end Alembic commands ###
