"""empty message

Revision ID: f31a3bf15832
Revises: 368d12da26fd
Create Date: 2024-10-05 18:11:29.443676

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f31a3bf15832"
down_revision: Union[str, None] = "368d12da26fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "news",
        sa.Column(
            "is_ticker_checked",
            sa.Boolean(),
            nullable=True,
            server_default=sa.text("false"),
        ),
    )
    op.drop_column("news_to_stock_symbol", "created_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "news_to_stock_symbol",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("news", "is_ticker_checked")
    # ### end Alembic commands ###
